[menu]
background                = "#212423"
background-alpha          = 1.0
text                      = "#FFFFFF"
border                    = "hyprland.active-border"
border-alpha              = 1.0
border-width              = 3
scrim                     = "#212423"
scrim-alpha               = 0.5
selected-background       = "#FFFFFF"
selected-background-alpha = 0.08
selected-text             = "#0DC7CB"
selected-border           = "hyprland.active-border"
selected-border-alpha     = 0.25
